# fly.toml app configuration file generated for matikkasovellus-tsoha on 2023-11-19T20:06:53+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "matikkasovellus-tsoha"
primary_region = "ams"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
